name: Publish Website

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render website
      uses: quarto-dev/quarto-actions/render@v2

    - name: Publish website
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
